[meta]
  title = "Agent Function Calling"
  description = "Basic demo for using Deepgram to call functions in a Voice Agent"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Agent Function Calling"
  language = "Python"
  framework = "Flask"

[build]
  command = "pipenv install -r requirements.txt"

[config]
  sample = "sample.env" # the example config file
  output = ".mock_data_outputs/" # the file that we will generate using their API

[post-build]
  message = "The application will be available at http://localhost:5000." # message to give users once setup is complete